### PR TITLE
feat!: update database to reflect schema changes

### PR DESCRIPTION
**Pull request by korikuzma**
Original work for this was done in #264 . This was incomplete. So starting a fresh PR

@jsstevenson This could use a new set of eyes.

`python3 -m pytest tests/unit/harvesters/ tests/unit/transform/ tests/unit/database/`

* Update neo4j to 5.x driver
* Update database nodes and relationships
  * Dropped Variation Group. We can add back in new issue if we want to retain this
* Changed fixture scope in `tests/conftest.py` to `session`
* Cleaned up getting secret value

### CODE REVIEW

**Comment by korikuzma** [comment]
I don't want to open/merge until I confirm things are working in #193

**Comment by jsstevenson** [comment]
I think the version pins here need to be restricted a bit more -- I'm getting this error upon fresh install

```
[ epic-231-db ⚙ venv] ~/code/metakb % python3 metakb/cli.py 
Traceback (most recent call last):
  File "/Users/jss009/code/metakb/metakb/cli.py", line 15, in <module>
    from disease.database import Database as DiseaseDatabase
ImportError: cannot import name 'Database' from 'disease.database' (/Users/jss009/code/metakb/venv/lib/python3.12/site-packages/disease/database/__init__.py). Did you mean: 'database'?
```

Might be prudent to just pin specific versions of the normalizers for now (also this is orthogonal to this specific issue)

**Comment by korikuzma** [comment]
@jsstevenson Oh sorry, I forgot to mention that is being done in #244. I had initial work on it, but haven't pushed. I plan to do this after these and your PRs get merged

**Comment by jsstevenson** [comment]
@korikuzma perfect! you're way ahead of me!

**Pull request merged**
